name: Build and publish Docker Image
on:
  push:
    tags: 
      - v*.*.*

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest    
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:          
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Set environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1        
            
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
        
      - name: Build and push Docker image x86_64
        run: docker buildx build --platform linux/amd64,linux/arm64 . -t "lucaslehnen/conversao-temperatura:${{ env.RELEASE_VERSION }}" --push          

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
